### ISSUE TITLE
Compatibility on windows

### ISSUE THREAD

**Issue by ykyuen** [ryanolsonx/gulp-dev#1]
Thanks for this great plugin, it works fine on Mac. but my colleague is a windows user and we found that the replacement doesn't work on windows. No error and warnings in the gulp output.

Anyone has a similar issue?

**Comment by ryanolsonx** [comment]
I haven't seen the issue reported.  I just tested it out and I am seeing what you're talking about.  I'll look into it.

**Comment by ryanolsonx** [comment]
This should be fixed now.
